### ISSUE TITLE
Optional Number Field

### ISSUE THREAD

**Issue by somnathguha** [sothach/isotypes#1]
Optional Number Field is throwing exception when data is not provided.

**Comment by sothach** [comment]
Can you give me sample code  / data so I can create a regression test & fix?
thx

**Comment by somnathguha** [comment]
In Context XML following configuration I am using:
"<iso:message type="0200" name="Transaction Request">
            <iso:field f="2" name="accountNumber" desc="Primary Account Number" dim="llvar(19)" type="an"/>
            <iso:field f="3" name="processingCode" desc="Processing Code" dim="fixed(6)" type="n" optional="true" />
        /iso:message"

and below is my JAVA Code:

Map<Integer, Object> params = new HashMap<Integer, Object>() {
            {
                put(2, "921100FFFFFFFFF6330");
            }
        };

Message message = bankMessages.createByNumbers(MTI.create("0200"), params);
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        bankMessages.writeToStream(message, baos);
        byte[] dataArr = baos.toByteArray();

Above code is throwing NullPointer exception.

I think I made a mistake. This comment should be for ISOType 2. Comments moving there.

**Comment by somnathguha** [comment]
Closing this issue and openning a new one under isotypes 2
